# Generated by Django 4.2.4 on 2023-09-05 10:09

from django.db import migrations, models
from django.utils.text import slugify

def set_default_slugs(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    Category = apps.get_model('blog', 'Category')
    Tag = apps.get_model('blog', 'Tag')

    for blog in Blog.objects.all():
        if not blog.slug:
            blog.slug = slugify(blog.title)
            blog.save()

    for category in Category.objects.all():
        if not category.slug:
            category.slug = slugify(category.name)
            category.save()

    for tag in Tag.objects.all():
        if not tag.slug:
            tag.slug = slugify(tag.name)
            tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_is_deleted_delete_deletedblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
        migrations.RunPython(set_default_slugs),
    ]
